### ISSUE TITLE
Error: cannot finalize before all snapshot resources are uploaded

### ISSUE THREAD

**Issue by ozyx** [percy/cli#1114]
## The problem

We encountered this percy client error on [a recent build](https://app.circleci.com/pipelines/github/nasa/openmct/14016/workflows/59b8ca6e-1041-457f-b844-835ce4681969/jobs/53669) which caused it to fail:

```
[percy:client] Finalizing snapshot 1259268152... (269ms)
[percy:core] Uploading 2 snapshots...[percy:core] Uploading 2 snapshots...[percy:core] Uploading 2 snapshots...[percy:core] Uploading 2 snapshots...[percy:core] Uploading 2 snapshots...[percy:core] Uploading 2 snapshots...[percy:core] Uploading 2 snapshots...[percy:core] Uploading 2 snapshots...[percy:core] Uploading 0 snapshots...[percy:core] Uploading 0 snapshots...[percy:core:browser] Closing browser (139ms)
[percy:core:browser] Browser closed (22ms)
[percy:client] Finalizing build 22594096... (0ms)
[percy:cli] Error: Finalizing build 22594096 failed: cannot finalize before all snapshot resources are uploaded. This is likely a client error, please make sure that content for all SHAs in 'missing-resources' from the snapshot response are uploaded before calling finalize.
    at handleFinished (file:///root/project/node_modules/@percy/client/dist/utils.js:176:17)
    at IncomingMessage.<anonymous> (file:///root/project/node_modules/@percy/client/dist/utils.js:193:27)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) (185ms)

Exited with code exit status 1
```

This happened on a build which was introducing no functional changes, nor changes to our visual tests.

## Environment

- Node version: 16.18.0
- `@percy/cli` version: 1.11.0
- Version of Percy SDK you’re using:
- If needed, a build or snapshot ID:
- OS version: Ubuntu 20.04.5 LTS
- Type of shell command-line [interface]:

## Details

See above

## Debug logs

More detailed logs can be found in the build logs [here](https://app.circleci.com/pipelines/github/nasa/openmct/14016/workflows/59b8ca6e-1041-457f-b844-835ce4681969/jobs/53669). (We run percy cli with debug mode on)

## Code to reproduce issue

N/A, happened at random.

**Comment by thomasmattheussen** [comment]
We're seeing the same problem  too since last week.

**Comment by thomasmattheussen** [comment]
Anybody got an idea? Our pipelines fail randomly because of this :/
