### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by martakarwacka** [percy/cli#1435]
If any of the tests fails, no screenshots are uploaded to the Percy dashboard. For screenshots to be visible, all tests must have a pass status. The error I get:

TypeError: Cannot read properties of undefined (reading 'id')
    at ChildProcess.<anonymous> (file:.../node_modules/@percy/cli-exec/dist/exec.js:137:52)
    at ChildProcess.emit (node:events:514:28)
    at cp.emit (...\node_modules\cross-spawn\lib\enoent.js:34:29)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

I tried:

- remove node_modules and add them again
- nodejs upgrade/downgrade
- upgrade/downgrade Percy version

**Comment by itsjwala** [comment]
Please share a reproducible sample, current information isn't helpful for us to help.

Going ahead and closing this issue, you can create a fresh issue following our issue template.
