### ISSUE TITLE
Error: Can't resolve reference /snapshot#/properties/name from id /config/static with 1.0.0-beta.59

### ISSUE THREAD

**Issue by rossta** [percy/cli#433]
In Circle CI, I receive an error when attempting to run tests with `percy exec` under version 1.0.0-beta.59. With version 1.0.0-beta.58, tests run with `percy exec` successfully.

Here is some additional info:

* Node version: 14.16.1
* Yarn version: 1.22.5
* CircleCI version 2.1, image: circleci/ruby:2.7-node
* Integration: percy-capybara 5.0.0 (Ruby gem)

Here is a detailed error:

```
#!/bin/bash -eo pipefail
DEBUG=* yarn percy exec -- bundle exec rspec
yarn run v1.22.5
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ /home/circleci/my_app/node_modules/.bin/percy exec bundle exec rspec
  @oclif/config reading core plugin /home/circleci/my_app/node_modules/@percy/cli +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli/oclif.manifest.json +4ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli/.oclif.manifest.json +1ms
  @oclif/config reading user plugins pjson /home/circleci/.local/share/@percy/cli/package.json +0ms
  @oclif/config loadJSON /home/circleci/.local/share/@percy/cli/package.json +1ms
  @oclif/config loading plugins [
  '@percy/cli-config',
  '@percy/cli-exec',
  '@percy/cli-build',
  '@percy/cli-snapshot',
  '@percy/cli-upload',
  '@oclif/plugin-help'
] +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli/package.json +3ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/package.json +1ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/package.json +1ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/package.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/package.json +0ms
  @oclif/config reading core plugin /home/circleci/my_app/node_modules/@percy/cli-config +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-config/package.json +1ms
  @oclif/config reading core plugin /home/circleci/my_app/node_modules/@percy/cli-exec +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-exec/package.json +0ms
  @oclif/config reading core plugin /home/circleci/my_app/node_modules/@percy/cli-snapshot +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-snapshot/package.json +0ms
  @oclif/config reading core plugin /home/circleci/my_app/node_modules/@percy/cli-build +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-build/package.json +0ms
  @oclif/config reading core plugin /home/circleci/my_app/node_modules/@percy/cli-upload +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-upload/package.json +0ms
  @oclif/config reading core plugin /home/circleci/my_app/node_modules/@oclif/plugin-help +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@oclif/plugin-help/package.json +1ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-config/oclif.manifest.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-exec/oclif.manifest.json +1ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-snapshot/oclif.manifest.json +1ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-build/oclif.manifest.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@percy/cli-upload/oclif.manifest.json +0ms
  @oclif/config loadJSON /home/circleci/my_app/node_modules/@oclif/plugin-help/oclif.manifest.json +1ms
  @oclif/config:@percy/cli-config using manifest from /home/circleci/my_app/node_modules/@percy/cli-config/oclif.manifest.json +0ms
  @oclif/config:@percy/cli-exec using manifest from /home/circleci/my_app/node_modules/@percy/cli-exec/oclif.manifest.json +0ms
  @oclif/config:@percy/cli-snapshot using manifest from /home/circleci/my_app/node_modules/@percy/cli-snapshot/oclif.manifest.json +0ms
  @oclif/config:@percy/cli-build using manifest from /home/circleci/my_app/node_modules/@percy/cli-build/oclif.manifest.json +0ms
  @oclif/config:@percy/cli-upload using manifest from /home/circleci/my_app/node_modules/@percy/cli-upload/oclif.manifest.json +0ms
  @oclif/config:@oclif/plugin-help using manifest from /home/circleci/my_app/node_modules/@oclif/plugin-help/oclif.manifest.json +0ms
  @oclif/config config done +11ms
  @oclif/config start init hook +1ms
  percy:@percy/cli-exec:hooks:init start /home/circleci/my_app/node_modules/@percy/cli-exec/dist/hooks/init +0ms
  percy:@percy/cli-snapshot:hooks:init start /home/circleci/my_app/node_modules/@percy/cli-snapshot/dist/hooks/init +0ms
  percy:@percy/cli-upload:hooks:init start /home/circleci/my_app/node_modules/@percy/cli-upload/dist/hooks/init +0ms
  percy:@percy/cli-exec:hooks:init done +197ms
  percy:@percy/cli-snapshot:hooks:init done +53ms
  @oclif/config init hook done +426ms
  percy init version: @oclif/command@1.8.0 argv: [ 'exec', 'bundle', 'exec', 'rspec' ] +0ms
  @oclif/config runCommand exec [ 'bundle', 'exec', 'rspec' ] +5ms
  @oclif/config:@percy/cli-exec require /home/circleci/my_app/node_modules/@percy/cli-exec/dist/commands/exec/index.js +433ms
(node:1256) Error Plugin: @percy/cli: can't resolve reference /snapshot#/properties/name from id /config/static
module: @oclif/config@1.17.0
task: runHook init
plugin: @percy/cli
root: /home/circleci/my_app/node_modules/@percy/cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Error Plugin: @percy/cli: can't resolve reference /snapshot#/properties/name from id /config/static
    at Object.code (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/vocabularies/core/ref.js:21:19)
    at keywordCode (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:185:25
    at CodeGen.code (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at schemaKeywords (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:185:13)
    at typeAndKeywords (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:128:5)
    at subSchemaObjCode (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:115:5)
    at subschemaCode (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:91:13)
    at KeywordCxt.subschema (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:428:9)
module: @oclif/config@1.17.0
task: runHook init
plugin: @percy/cli
root: /home/circleci/my_app/node_modules/@percy/cli
See more details with DEBUG=*
Error: can't resolve reference /snapshot#/properties/name from id /config/static
    at Object.code (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/vocabularies/core/ref.js:21:19)
    at keywordCode (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:185:25
    at CodeGen.code (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at schemaKeywords (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:185:13)
    at typeAndKeywords (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:128:5)
    at subSchemaObjCode (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:115:5)
    at subschemaCode (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:91:13)
    at KeywordCxt.subschema (/home/circleci/my_app/node_modules/@percy/config/node_modules/ajv/dist/compile/validate/index.js:428:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by rossta** [comment]
@Robdel12 Thanks, I missed that fix. I can confirm it works for me. Apologies for the duplicate issue!
