### ISSUE TITLE
certificate is not yet valid

### ISSUE THREAD

**Issue by cancan101** [percy/cli#544]
Getting this error:
```
[percy:client] Creating a new build... (28ms)
[percy:core:install] Downloading Chromium 885264...
[percy:cli:snapshot] Error: certificate is not yet valid
    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) (1526ms)
Error: Command failed with exit code 1: npx percy snapshot -v snapshots.yml
    at makeError (/home/runner/work/app/app/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/app/app/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
```

**Comment by Robdel12** [comment]
Hey @cancan101! That likely means the certificate isn't valid _or_ the systems time is incorrect? Googling that error suggests the certificates time is wrong or the systems time is wrong
